provider: gcp

gcp:
  project_id: rfrench
  region: us-central1
  queue_name: parallel-addition-queue
  job_id: parallel-addition-job
  image: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20250409
  service_account: rms-cloud-run@rfrench.iam.gserviceaccount.com
  startup_script: |
    apt-get update -y
    apt-get install -y python3 python3-pip python3-venv git
    cd /root
    git clone https://github.com/SETI/rms-cloud-run.git
    cd rms-cloud-run
    git checkout initial_version
    python3 -m venv venv
    source venv/bin/activate
    pip install -e .
    pip install -r examples/parallel_addition/requirements.txt
    export ADDITION_OUTPUT_DIR=gs://rfrench-test-bucket/addition-results
    export ADDITION_TASK_DELAY=1
    python3 examples/parallel_addition/worker_addition.py
