provider: gcp

gcp:
  job_id: parallel-addition-job
  project_id: rfrench
  region: us-central1
  boot_disk_types: [pd-standard, pd-ssd]
  service_account: rms-cloud-run@rfrench.iam.gserviceaccount.com
  startup_script: |
    apt-get update -y
    apt-get install -y python3 python3-pip python3-venv git
    cd /root
    git clone https://github.com/SETI/rms-cloud-tasks.git
    cd rms-cloud-tasks
    git checkout rf_250523
    python3 -m venv venv
    source venv/bin/activate
    pip install -e .
    pip install -r examples/parallel_addition/requirements.txt
    export ADDITION_OUTPUT_DIR=gs://rfrench-test-bucket/addition-results
    export ADDITION_TASK_DELAY=0
    python3 examples/parallel_addition/worker_addition.py
