# Cloud Tasks configuration with regions specified

aws:
  region: us-west-2
  access_key: YOUR_AWS_ACCESS_KEY
  secret_key: YOUR_AWS_SECRET_KEY

gcp:
  # project_id: your-gcp-project-id
  project_id: rfrench
  region: us-central1
  zone: us-central1-a
  # credentials_file: /path/to/gcp-credentials.json

azure:
  subscription_id: your-azure-subscription-id
  resource_group: your-resource-group
  location: eastus
  tenant_id: your-tenant-id
  client_id: your-client-id
  client_secret: your-client-secret