# Multi-Cloud Task Processing System Configuration

# AWS Configuration
aws:
  access_key: YOUR_AWS_ACCESS_KEY
  secret_key: YOUR_AWS_SECRET_KEY
  region: us-west-2

# GCP Configuration
gcp:
  project_id: YOUR_GCP_PROJECT_ID
  credentials_file: /path/to/your-gcp-credentials.json
  zone: us-central1-a

# Azure Configuration
azure:
  subscription_id: YOUR_AZURE_SUBSCRIPTION_ID
  tenant_id: YOUR_AZURE_TENANT_ID
  client_id: YOUR_AZURE_CLIENT_ID
  client_secret: YOUR_AZURE_CLIENT_SECRET
  location: eastus
  resource_group: cloud-run-rg