# Cloud Tasks configuration without regions specified
# This will trigger automatic cheapest region selection

aws:
  access_key: YOUR_AWS_ACCESS_KEY
  secret_key: YOUR_AWS_SECRET_KEY
  # No region specified - will use cheapest

gcp:
  project_id: your-gcp-project-id
  credentials_file: /path/to/gcp-credentials.json
  # No region specified - will use cheapest

azure:
  subscription_id: your-azure-subscription-id
  resource_group: your-resource-group
  tenant_id: your-tenant-id
  client_id: your-client-id
  client_secret: your-client-secret
  # No location specified - will use cheapest